-- MySQL Script generated by MySQL Workbench
-- 10/10/17 14:24:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TesteCampeonato
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TesteCampeonato
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TesteCampeonato` DEFAULT CHARACTER SET utf8 ;
USE `TesteCampeonato` ;

-- -----------------------------------------------------
-- Table `TesteCampeonato`.`Times`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TesteCampeonato`.`Times` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `pratrocinadores` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TesteCampeonato`.`Jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TesteCampeonato`.`Jogos` (
  `id` INT NOT NULL,
  `data` DATE NOT NULL,
  `nome_estadio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TesteCampeonato`.`Jogam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TesteCampeonato`.`Jogam` (
  `time1_id` INT NOT NULL,
  `jogos_id` INT NOT NULL,
  `time2_id` INT NOT NULL,
  PRIMARY KEY (`time1_id`, `jogos_id`, `time2_id`),
  INDEX `fk_Jogam_Times1_idx` (`time2_id` ASC),
  INDEX `fk_Jogam_Jogos1_idx` (`jogos_id` ASC),
  CONSTRAINT `fk_Jogam_Times`
    FOREIGN KEY (`time1_id`)
    REFERENCES `TesteCampeonato`.`Times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogam_Times1`
    FOREIGN KEY (`time2_id`)
    REFERENCES `TesteCampeonato`.`Times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogam_Jogos1`
    FOREIGN KEY (`jogos_id`)
    REFERENCES `TesteCampeonato`.`Jogos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TesteCampeonato`.`Resultado_Jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TesteCampeonato`.`Resultado_Jogos` (
  `id_jogos` INT NOT NULL,
  `times_id` INT NOT NULL,
  `gols` INT NOT NULL,
  INDEX `fk_Resultado_Jogos_Times1_idx` (`times_id` ASC),
  PRIMARY KEY (`id_jogos`, `times_id`),
  CONSTRAINT `fk_Resultado_Jogos_Jogos1`
    FOREIGN KEY (`id_jogos`)
    REFERENCES `TesteCampeonato`.`Jogos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resultado_Jogos_Times1`
    FOREIGN KEY (`times_id`)
    REFERENCES `TesteCampeonato`.`Times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TesteCampeonato`.`Classificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TesteCampeonato`.`Classificacao` (
  `colocacao` VARCHAR(45) NOT NULL,
  `id_time` INT NOT NULL,
  `nome_time` VARCHAR(45) NOT NULL,
  `pontos` INT NOT NULL,
  `vitorias` INT NOT NULL,
  `derrotas` INT NOT NULL,
  `total_gols` INT NOT NULL,
  PRIMARY KEY (`id_time`),
  CONSTRAINT `fk_Classificacao_Times1`
    FOREIGN KEY (`id_time`)
    REFERENCES `TesteCampeonato`.`Times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
